### PR TITLE
handshake: docmuent peerId and sentTime

### PR DESCRIPTION
**Pull request by SurmanPP**

### CODE REVIEW

**Comment by SurmanPP** [comment]
I have to revise this. The header struct is a little bit wrong. This would be the right reference: https://github.com/lsalzman/enet/blob/1e80a78f481cb2d2e4d9a0e2718b91995f2de51c/protocol.c#L1011

**Comment by flp5** [comment]
thanks!
this is a very good notation change - please make all the other parts of the analysis conform to this new `--` notation

**Comment by SurmanPP** [comment]
The first 2 bytes are the peerId, sessionId and flags. The second 2 bytes can be the sentTime if the SENT_TIME flag is set(16th bit of peerId).

**Comment by flp5** [comment]
do you know if that flag is set?

**Comment by SurmanPP** [comment]
no in this case it is not

**Comment by SurmanPP** [comment]
Since this is pretty much revers-engineering ENet and we actually only want to know what SE does I'll close this.

**Pull request closed without merging**
